version: '3.8'
services:
  db:
    image: mariadb:latest
    restart: always
    ports:
      - "3300:3306"
    environment:
      MYSQL_DATABASE: 'te-emprego'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
